export type { IPopular } from './IPopular'
export type { IMediaList } from './IMediaList'
export type { IMovie } from './IMovie'
export type { ICredit } from './ICredit'
export type { IRecommendations } from './IRecommendations'
